name: Update Index

on:
  push:
    paths:
      - 'article/**.html'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Generate index.html
        run: python update_index.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html articles_data.json
          git commit -m "Update index with new articles" || echo "No changes to commit"
          git push
